SET FOREIGN_KEY_CHECKS=0 ;

DROP TABLE IF EXISTS `states` CASCADE
;

DROP TABLE IF EXISTS `types_insurance` CASCADE
;

DROP TABLE IF EXISTS `list_insured` CASCADE
;

DROP TABLE IF EXISTS `premiums_insurance` CASCADE
;

DROP TABLE IF EXISTS `indemnities_insurance` CASCADE;
DROP DATABASE IF EXISTS `Insurance_agency`;
SET FOREIGN_KEY_CHECKS=1 ;



